### ISSUE TITLE
Backends for mobile or other apps

### ISSUE THREAD

**Issue by augustl** [grand-decentral-station/concept#35]
Let's say you're implementing a mobile app. You want this mobile app to have a backend, for some reason. Perhaps for synchronization of data, perhaps to do things like computing results every hour on the server and displaying those results in the app - what do we know.

Should it be possible to somehow deploy an app to a GDS instance directly from the app, for use cases like this?

**Comment by lukasbestle** [comment]
There will be an administration API, so yeah, this will be possible!
The user would have to login to the server and could then let the app install something on the server.

**Comment by augustl** [comment]
You could imagine the app uses a mechanism to get access to your GDS, the code for the backend is embedded in the app itself, and that code is then shipped to and installed in the GDS. Perhaps it's better if the app sends an URL to the GDS instance, to make it easier for the vendor to always point to the most recent version of the app code, to have multiple versions depending on whether the GDS is hosted in windows, linux, etc etc.

Things like versioning and data migration should probably not be handled by GDS, but by the app provider themselves.

**Comment by lukasbestle** [comment]
Yeah, the app would just tell GDS to „install the app from the repository at this URL“ and to „enable the app for the user x“.

**Comment by augustl** [comment]
All that's really left to solve, then, is how to get permissions for that. Which can be done in a separate issue when the time comes, me thinks :)

**Comment by lukasbestle** [comment]
Hey, don’t close stuff. :D

I guess there would be an optional two-factor auth app where you would have to accept the change.
But I don’t think we really need it, as normally using the web interface or a native app would require it as well.
