### ISSUE TITLE
Email Server ip address

### ISSUE THREAD

**Issue by timkaechele** [grand-decentral-station/concept#44]
While the idea of having your own email server is really awesome, there could be a problem with the setup on self-hosted (@home) email servers. Many internet providers don't provide a static ip address to average customers. 
Big Email Providers like gmail, outlook, icloud, etc. don't accept emails sent from dynamic ip addresses, primarily because normally these emails are sent by viruses or botnets, not a big deal. But by setting up a email server behind a dynamic ip with the goal of a full featured email setup, the server could be condemned being a receive only setup.

**Comment by lukasbestle** [comment]
That's why this stuff would be implemented as app and not in the core.
But that's a valid point, yeah.

**Comment by timkaechele** [comment]
Implementing it as an app doesn't solve the actual problem. :smile:

**Comment by lukasbestle** [comment]
It does!
If it’s usable for the user is the user’s decision in that case. ;)

Anyway: We should maybe define a sync API between two GDS instances, so I could have a public server running at a web host all the time and my local box pulling all data from there. :)

**Comment by DerZyklop** [comment]
I dont see this as an GDS-issue. Its a general problem with mail-servers from dynamic customer IP's.

**Comment by lukasbestle** [comment]
Exactly.

**Comment by timkaechele** [comment]
It is a GDS issue, cause it is a fundamental part of the just works experience. If a user sets up an email server, he doesn't want to read anything about »Hey man sorry, doesn't work, you have the wrong ISP.«

Because everybody has two GDS instances running, just for fun. :D

No seriously. A possible solution could be a check of the ip address and an automatic SMTP relay to a GDS with static ip, as far as I understood it, all emails are encrypted anyway, so privacy shouldn't be a big problem. The owner of the static ip GDS could get a small fee for every delivered email. The dynamic ip GDS would be informed, that emails can only be sent via an SMTP relay (well you could make it a bit more non technical of course), because his setup doesn't allow sending emails, and that there is a solution that includes paying a small sending fee per 1/100/1000 emails, whatever.

**Comment by DerZyklop** [comment]
I stick to it. Its not a GDS issue. Even though it would be awesome if GDS could fix it. My first idea was to improve the setup of a DynDNS-Sever. I'm not that familiar with protocols, but what you explained here sounds like a DnyDNS-Service just for the email part. 

Next step would be a DynDNS-Service-App for those who have static IP's. This would open the doors to even easier setup of DynDNS on non-static-ip-GDS's.
Question here: Is it anyhow possible to build a kind of decentralized DynDNS-Network-thing?

**Comment by DerZyklop** [comment]
...dont know if i made this clear: 
When i have a static IP, i could install the mentioned "DynDNS-Service-App" in my machine to provide a DynDNS-service for other non-static-ip-GDS users. 

...lets call it "DynDNS-Provider-App"

**Comment by timkaechele** [comment]
Well DynDNS just adds a domain name to your dynamic ip, so it doesn't solve the email problem. It works by constantly updating the ip records of a domain. My email solution could work via an api(more suitable) or via a classical smtp-relay setup (could be a bit more complex). There could be a search for GDSs with static ip that allow "foreign" users to use their email server to send emails. The API could be inspired by http://www.mailgun.com/

**Comment by lukasbestle** [comment]
I agree with @DerZyklop that this is not a GDS issue - it's a general issue GDS can but does not have to solve.

But I really like the idea of SMTP relaying. I already wrote something about the "Discovery & monitoring server" in services.md; we could use a similar concept here, although we might want to make it a core API then.

**Comment by timkaechele** [comment]
> Sending and receiving emails should work out of the box. It needs an easy way to setup email…  – https://github.com/grand-decentral-station/concept/blob/master/concept/services.md

**Comment by lukasbestle** [comment]
Alright. :)
