### ISSUE TITLE
BTSync

### ISSUE THREAD

**Issue by sternenseemann** [grand-decentral-station/concept#9]
I saw BTSync under the category "Communication between servers" in links.md

IMO you shouldn't use it because it isn't FOSS and there's a commercial company behind.

**Comment by bastianallgeier** [comment]
I added the link to BTSync because I love the idea behind it. I agree though that the focus should be on 100% open-source parts.

**Comment by sternenseemann** [comment]
There are already attempts to replace it by a FOSS-Application: [jewel/clearskies](https://github.com/jewel/clearskies)

**Comment by bastianallgeier** [comment]
Tobias Tom already added clearskies as an alternative to the link list.
